### ISSUE TITLE
[Documentation] Add CNF Test Suite to Litmus adopters.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1002]
### Short description: 
- to add the CNF Test Suite as an open source project adopter of LitmusChaos solutions on https://github.com/litmuschaos/litmus/blob/master/ADOPTERS.md#cloud-native-oss-projects

### Tasks: 

- [ ] Draft Organization/use case for https://github.com/litmuschaos/litmus/blob/master/ADOPTERS.md#cloud-native-oss-projects
- [ ] Draft Our Story for a new file, to be called, https://github.com/litmuschaos/litmus/blob/master/adopters/organizations/cnftestsuite.md
- [ ] Draft CNF Test Suite description
- [ ] Draft "Why do we use Litmus" section
- [ ] Draft "How do we use Litmus" section
- [ ] Draft "Benefits in using Litmus" section

**Comment by lixuna** [comment]
DRAFT:
----

# For https://github.com/litmuschaos/litmus/blob/master/ADOPTERS.md#cloud-native-oss-projects

Organization
- [CNF Test Suite](https://github.com/cncf/cnf-testsuite) 

Usecase
- To validate the resilience of Cloud Native Network Functions (CNFs)

Details
- [Our Story](Our Story)

# Our Story - https://github.com/litmuschaos/litmus/blob/master/adopters/organizations/cnftestsuite.md

CNF Test Suite
---

The CNF Test Suite is an open source test suite for Cloud Native Network Function (CNF) developers and network operators to evaluate how well a telecom service (a platform or network application, aka CNF) follows cloud native principles and best practices, like resilience.

## Why do we use Litmus  
Subjecting the telecom services to chaos testing is useful in finding failure points and suggesting remediation steps toward improving resilience. Therefore, we chose LitmusChaos to create resilience tests in the CNF Test Suite. 

## How do we use Litmus  
By including LitmusChaos experiments in the CNF Test Suite's workload tests, we are able to subject telecom services to resiliences experiments including: **pod-network-duplication**, **pod-network-corruption**, **pod-io-stress**, **pod-memory-hog**, **pod-delete**, **disk-fill**, **pod-network-latency**, and more. This helps the end user see how their service behaves when exposed to common application failures.

## Benefits in using Litmus   
The benefits we see in LitmusChaos are: it is part of the CNCF ecosystem, it is designed for Kubernetes workloads, it has a vibrant community and it is well maintained.

**Comment by agentpoyo** [comment]
LGTM. :heavy_check_mark: 

@lixuna

**Comment by lixuna** [comment]
|[CNF Test Suite](https://github.com/cncf/cnf-testsuite)|To validate the resilience of Cloud Native Network Functions (CNFs)|[Our Story](adopters/organizations/cnftestsuite.md)|
