### ISSUE TITLE
[Documentation] create a RELEASES.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#107]
### [Documentation] create a RELEASES.md

**Short Description:**
- to create a RELEASES.md in the repo that describes the versioning and release process of CNF Conformance

**Location:** 
- github.com/cncf/cnf-conformance/blob/master/RELEASES.md

**Tasks:**
- [ ] Create an RELEASES.md	
- [ ]  Create an outline
- [ ]  Create a rough draft
- [ ]  Peer review of draft
- [ ]  Iterate as needed, peer review (optional)
- [x] Add content to RELEASES.md

**Comment by lixuna** [comment]
follow-up to #83

**Comment by taylor** [comment]
See https://hackmd.io/f7Op9FgJQqW2QQXb-tVRgg?view

**Comment by lixuna** [comment]
Example RELEASE.md files for reference:
- https://github.com/prometheus/prometheus/blob/master/RELEASE.md
- https://github.com/envoyproxy/envoy/blob/master/RELEASES.md
- https://github.com/containerd/containerd/blob/master/RELEASES.md
- https://github.com/jaegertracing/jaeger/blob/master/RELEASE.md

**Comment by lixuna** [comment]
release documentation was created on Oct 2, 2020 in https://github.com/cncf/cnf-testsuite/commit/6717f2b514fc4b2a7eb63a91a22b198167567cfb#diff-2b1b69303b927a484e02c7fad9fc87d0d3ff0dc22ae1da0ecd0dc935d922a23c

Closing issue as duplicate
