### ISSUE TITLE
[EPIC] review and update CNF_TESTSUITE_YML_USAGE.md 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1357]
**Is your feature request related to a problem? Please describe.**
- The  https://github.com/cncf/cnf-testsuite/blob/main/CNF_TESTSUITE_YML_USAGE.md is part of the cert instructions
- It was last updated in June 2021 and may be out of date

**Describe the solution you'd like**

- [ ] Review and make notes to problems found, see https://hackmd.io/V70iQ_V_TIWa8imUL6AkfQ?view
- [ ] Test if documentation is valid
- [ ] Create separate issues for bug fixes
- [ ] Prioritize issues for cert

**Comment by taylor** [comment]
Estimate of effort:
- @denverwilliams 8
- @agentpoyo 8
- taylor 8
- @lixuna 8

**Comment by denverwilliams** [comment]
Completed Tickets: 

https://github.com/cncf/cnf-testsuite/issues/1430

**Comment by agentpoyo** [comment]
Check #1430 for any AC or review notes.
