### ISSUE TITLE
EPIC - QA v0.29.0 issues in READY FOR PEER REVIEW column

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1449]
### QA v0.29.0 issues in READY FOR PEER REVIEW column

Tasks:
- [x] Go through Acceptance Criteria
- [x] Accept as-is and move to "Reviewer Approved" column
- [ ] or Create new bug issues for issues found (to be planned/prioritized)
