### ISSUE TITLE
[Maintenance] EPIC: Plan software updates of 3rd party tools Q2 2022 (June 1-June 30) 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#1532]
### [Q2 2022 Maintenance] EPIC: Update versions of 3rd party tools Q2 2022 (June 1-June 30) 

**Describe the maintenance item**
- developer planning meeting
- check for latest release of third parties (including but not limited to: Kubescape, Kyverno, Litmus, Sonobuoy)
- check compatibility with dependencies
- create a new GitHub issue for each third party tool
- update CNF Test Suite with one minor release behind the latest

**Expected behavior**
- the CNF Test Suite will function as expected after updating third party tools

**How will this be tested? aka Acceptance Criteria (optional)**

- [ ] All documentation is updated to mention the updated software version
- [ ] Install works as expected
- [ ] Running `all` tests works as expected
- [ ] Running `workload` works as expected
- [ ] Running `platform` works as expected
- [ ] Running `cert` works as expected
- [ ] Running individual test categories works as expected
- [ ] Running individual tests works as expected
- [ ] tbd, add more expectations as needed

**Comment by HashNuke** [comment]
Kubescape was updated as a part of #1551. Was required to resolve #1440.

**Comment by agentpoyo** [comment]
Kyverno #1729 acceptance criteria @ https://github.com/cncf/cnf-testsuite/pull/1729#issuecomment-1423406522

**Comment by agentpoyo** [comment]
Sonobouy #1730 acceptance criteria @ https://github.com/cncf/cnf-testsuite/pull/1730#issuecomment-1423408809

**Comment by lixuna** [comment]
@williscool please create [new issues](https://github.com/cncf/cnf-testsuite/issues/new/choose) for software updates, like kind for example.
