### ISSUE TITLE
[Feature] Rename "statelessness" test category name to "State" in documentation

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#264]
**Is your feature request related to a problem? Please describe.**
- [CNF WG's best practices](https://github.com/cncf/cnf-wg/blob/main/doc/best_cnf_dev.md#60-state) lists this test category as "State"

**Describe the solution you'd like**
- Update markdown docs to change "statelessness" to "state" [per CNF WG's best practices](https://github.com/cncf/cnf-wg/blob/main/doc/best_cnf_dev.md#60-state)
- Search for "statelessness" in repo
- Filter to view [Markdown files](https://github.com/cncf/cnf-testsuite/search?l=Markdown&q=statelessness) in search results
- As of April 28, 2021, there are 6 Markdown files that contain the word "statelessness"

**Tasks**

- [ ] Update /TEST-CATEGORIES.md
- [ ]  /PSEUDO-CODE.md, 
- [ ] /USAGE.md, 
- [ ] /README.md, 
- [ ] .github/ISSUE_TEMPLATE/new-platform-test.md, 
- [ ] .github/ISSUE_TEMPLATE/new-workload-test.md

**How will this be tested?**
- Search for "statelessness" in repo
- Filter to view Markdown files
- After the documentation is updated in this issue, there should be 0 results for "statelessness" in markdown files 

**Out of scope**
- Updating code is not included in this issue. 
- Changes to YAML and Crystal files are not included in this issue. 
- Changes to code will be handled in #744

**Comment by lixuna** [comment]
The CNF WG calls this category "State" in https://github.com/cncf/cnf-wg/blob/main/doc/best_cnf_dev.md#60-state

**Comment by HashNuke** [comment]
Attempted as a part of #838. Would love for someone to pick it up for review and share any feedback.
I haven't marked the checklist on this issue because I am not sure if the PR is good yet.

**Comment by agentpoyo** [comment]
`Statelessness` not found in documentation, all have been updated to `State`.
