### ISSUE TITLE
[Process] Add aliases for larger commands, ie. long test names

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#267]
### [Process] Add aliases for larger commands

**Short description:**
- to improve the developer experience, add aliases to long test names like `volume_hostpath_not_found` in#159 

**Tasks:**

- [ ]  update process
- [ ]  update documentation
- [ ]  TBD

**QA tasks**

Dev Review: 
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Needs Peer Review` column  
   - [ ] create Pull Request and follow check list
   - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:
- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes, 
   - [ ] move to `Reviewer Approved` column
   - [ ] Approve pull request
- [ ] if no, 
   - [ ] document what did not go as expected, including error messages and screenshots (if possible)
   - [ ] Add comment to pull request
   - [ ] request changes to pull request
