### ISSUE TITLE
[CodeReadability] rename the cluster name variable from `$TIME` to `CLUSTERNAME` throughout the repo

### ISSUE THREAD

**Issue by wavell** [cncf/cnf-testsuite#411]
# [Enhancement] Rename the cluster name variable from $TIME to CLUSTERNAME throughout the repo

## Problem:

@denverwilliams I was a bit confused by $TIME and thought no cluster name was being used.  TIME is the cluster name.  

## Suggestion for improvement:

I suggest the variable be renamed throughout. Eg.
```
             export TIME=$(date +%s)$RANDOM
```

to

```
            export CLUSTERNAME=$(date +%s)$RANDOM
```

_Originally posted by @taylor in https://github.com/cncf/cnf-testsuite/pull/408#r494476577_

### Tasks:
- [ ] review [CONTRIBUTING.md](contributing.md)
- [ ] search for the cluster name variable called `TIME` in the cnf-testsuite repo
- [ ] rename the cluster name variable from `TIME` to `CLUSTERNAME`
- [ ] submit a pull request
- [ ] Move issue to "Needs Peer Review" column/ status of project board

### How this will be tested:
- [ ] search for the cluster name variable called `TIME` in the cnf-testsuite repo
- [ ] should see 0 results matching the variable name `TIME` (variable name only, not to be confused with other time limits, elapsed time, timeouts, test names)

**Comment by lixuna** [comment]
@taylor where exactly in the code did you notice this problem? I want to make sure that the description of this ticket is clear to the contributor before we mark it as a good first issue.

**Comment by taylor** [comment]
@lixuna apparently this ticket is invalid as we moved to Github actions and there are no references to TIME as the cluster name that I found.  https://github.com/cncf/cnf-testsuite/blob/main/.github/workflows/actions.yml#L222-L232

The original code referenced was in the Travis CI configuration (.travis.yml). 

Closing this ticket as invalid.
