### ISSUE TITLE
EPIC: [Resilience]Test if a CNF application is resilient with litmus chaos experiments.

### ISSUE THREAD

**Issue by uditgaurav** [cncf/cnf-testsuite#499]
### EPIC: Resilience testing: Litmus Chaos tests (Network / Resource / IO)

Test Category: Resilience

Type of test (static or runtime) = runtime

## Type of test

- Litmus has a number of chaos experiments hosted on https://hub.litmuschaos.io/ which can be used to test the resiliency of a CNF application. The tests can be categorized as:

  - **Network Chaos Test**: This includes the chaos to disrupt network connectivity to CNF pods.
  - **Resource Chaos Test**: This includes the resource exhaustion of the CNF pod or node on which the pods are scheduled. 
  - **IO / Disk Chaos Test**: The test will give an IO spike on the CNF application pod or node. Chaos like Disk Fill can fill up Ephemeral Storage of the CNF Pod.
  - **Other Chaos Test**: This includes tests like killing CNF replication and checking the recovery(_pod-delete_). Killing the container on the CNF application (_container_kill_).

- For the POC I have added a pod-network-latency experiment which will inject network latency into the application pod. 

## Test code

- The test code is added in [this forked CNF repo](https://github.com/uditgaurav/cnf-conformance/tree/add_litmus_pod_network_latency). The code includes the following steps:

  - Created **litmuschaos_setup.cr** (in  cnf-conformance/src/tasks) : It contains litmus setup/cleanup tasks along with some functions used to run chaos. 

  - Added **pod-network-latency** experiment (in cnf-conformance/src/tasks/workload/resilience.cr): This adds the chaos experiment which also contains a CR template along with other tests.

  - Adding the test in `points.yml`.

 

Tasks:
- [X] Add a quick overview of the type of test you are researching/creating a POC for
- [ ] Investigate potential tools for implementation and document findings, https://hackmd.io/new  (add link to ticket)
- [ ] Select a tool to use, minimal/least effort, and add selection to ticket
- [X] Add new POC test code
- [X] Add comment suggesting updates as needed for:
  - [ ] the [test categories markdown](https://github.com/cncf/cnf-conformance/blob/master/TEST-CATEGORIES.md)
  - [ ] the [psuedo code markdown](https://github.com/cncf/cnf-conformance/blob/master/PSEUDO-CODE.md)
  - [ ] slide content updates, LINK_TO_UPDATES
  - [ ] the [README](https://github.com/cncf/cnf-conformance/blob/master/README.md)
- [ ] Tag 1 or more people to peer review

**Comment by uditgaurav** [comment]
## Disk Fill Test Logs

```
root@ip-172-31-31-45:~/cnf-conformance# LOG_LEVEL=error ./cnf-conformance disk_fill verbose
2021-03-17T19:40:16.061201Z   INFO - Results.file
2021-03-17T19:40:16.061322Z   INFO - file exists?:false

Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.engineStatus}'
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
status_code: 0
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
status_code: 0
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
status_code: 0
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
status_code: 0
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
status_code: 0
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
status_code: 0
Checking experiment status  kubectl get chaosengine.litmuschaos.io coredns-coredns-3 -o jsonpath='{.status.experiments[0].status}'
Checking experiment verdict  kubectl get chaosresults.litmuschaos.io coredns-coredns-3-disk-fill -o jsonpath='{.status.experimentstatus.verdict}'
Checking experiment verdict  kubectl get chaosresults.litmuschaos.io coredns-coredns-3-disk-fill -o jsonpath='{.status.experimentstatus.verdict}'
status_code: 0
verdict: Pass
✔️  PASSED: disk_fill chaos test passed 🗡️💀♻️
```
