### ISSUE TITLE
[EPIC: Feature] Optimize CNF Test Suite for offline (Air gapped) usage

### ISSUE THREAD

**Issue by clementnuss** [cncf/cnf-testsuite#585]
Having recently used the tool to test some closed-source CNFs on a real Telco infrastructure, I have had a hard time working with the fact that cnf-conformance is heavily relying on internet access to be used.
Indeed, in our infrastructure, our servers are in an "air-gapped" setup: there is no internet access for security reasons.

As a workaround and because this was for testing purposes, it was possible to have a proxy access to the resources needed by cnf-conformance, and it was in the end possible to use the tool.

**Describe the solution you'd like**
Ideally, the release would contain all needed files (`point.yaml`, `tools/`, etc.) to simplify air-gapped deployment, and the installation of e.g. `chaos-mesh` would not always trigger a `git clone` of `chaos-mesh` repository.

**Describe alternatives you've considered**
Using a proxy to provide those files, but might not always be possible to air-gapped environments.

---

Tickets for [MVP solution (milestone #9)](https://github.com/cncf/cnf-testsuite/milestone/9):
- 👀 [[EPIC - Feature] Make an image deployment tool that makes the images available to the private cluster #773](https://github.com/cncf/cnf-testsuite/issues/773)
    - 👀 [[Feature] Bootstrap a cluster #782](https://github.com/cncf/cnf-testsuite/issues/782)
    - 👀 [[Feature] Publish tarball #780](https://github.com/cncf/cnf-testsuite/issues/780)
- 👀  [[Feature] Make a tool that tarballs the containerized tools used by the testsuite. #763](https://github.com/cncf/cnf-testsuite/issues/763)
- 👀 [[Feature] Use the airgap tool to tarball (and untar) the helm charts, prerequisite binaries, and upstream testing binaries #772](https://github.com/cncf/cnf-testsuite/issues/772) 
- 👀 [Feature] Tar and upload helm directories, and manifest files #789

Status: 2021-06-03 All in peer review for next release

**Comment by sdesbure** [comment]
Hey, I've got the same issue :)

**Comment by wavell** [comment]
https://hackmd.io/qCAvHzzDS9aXU2q4lxNzYQ @taylor

**Comment by taylor** [comment]
@sdesbure do y'all run your own private image registry?  If so can you share what it is? For example is it:
- [ ] [Vanilla Docker image registry](https://docs.docker.com/registry/)
- [ ] [Harbor](https://goharbor.io/)
- [ ] [Sonatype Nexus](https://www.sonatype.com/products/repository-oss)

**Comment by sdesbure** [comment]
Hi @taylor, it's a Sonatype Nexus (deployed in a "tool zone" kubernetes)

**Comment by taylor** [comment]
@clementnuss we are working on this issue in chunks in with smaller feature enhancements. Here are a couple of those tickets
- [[Feature] Make a tool that tarballs the containerized tools used by the testsuite. #763](https://github.com/cncf/cnf-testsuite/issues/763)
- [[Feature] Use the airgap tool to tarball (and untar) the a list of tools #772](https://github.com/cncf/cnf-testsuite/issues/772)
- [[Feature] Make an image deployment tool that makes the images available to the private cluster #773](https://github.com/cncf/cnf-testsuite/issues/773)

**Comment by taylor** [comment]
@clementnuss, @sdesbure we are working on adding air gapped support in chunks in with smaller feature enhancements. 

Here are a few of those tickets
- [[Feature] Make a tool that tarballs the containerized tools used by the testsuite. #763](https://github.com/cncf/cnf-testsuite/issues/763)
- [[Feature] Use the airgap tool to tarball (and untar) the a list of tools #772](https://github.com/cncf/cnf-testsuite/issues/772)
- [[Feature] Make an image deployment tool that makes the images available to the private cluster #773](https://github.com/cncf/cnf-testsuite/issues/773)

**Comment by taylor** [comment]
Background planning for MVP

1. Make a tarball wrapper tool that can be used by the cnf-testsuite binary
a. (make a ticket for a this, with acceptance criteria)
2. Make a tarball tool that tarballs containerized tools that we maintain or are maintained upstream(dockerd images). https://github.com/cncf/cnf-testsuite/issues/763
a. (make a ticket for a this, with acceptance criteria)
3. Make an option in the tarball tool that tarballs all manifest & helm charts needed to install local and upstream tools.
a. (make a ticket for a this, with acceptance criteria)
4. Make an option in the tarball tool to apply files that use kubectl’s http option (make kubectl apply manifests available on disk instead of remote)
a. (make a ticket for a this, with acceptance criteria)
5. Make an image deployment tool that makes the images available to the private cluster
a. (make a ticket for a this, with acceptance criteria)
See https://github.com/cncf/cnf-testsuite/issues/773
6. Use the tools to:
a. Tarball containerized tools that we maintain (dockerd images) (dockerd)
b. Tarball containerized tools that are maintained upstream (chaosmesh image, litmus image)
c. Tarball all k8s manifests & helm charts that we maintain.
d. Tarball all k8s manifests & helm charts that are maintained upstream.
a. (make a ticket for a this, with acceptance criteria)
7. Include steps for extracting and installing above in a readme
a. (make a ticket for a this, with acceptance criteria)

**Comment by wavell** [comment]
### Acceptance Criteria for peer review
---
### Documentation is updated:
- [ ] cnf-conformance.yml documentation update 

###  Common steps
- [ ]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-conformance/blob/master/KIND-INSTALL.md) will work as well
- [ ]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [ ]  As a peer reviewer, check that PR passes in GitHub Actions
     - [ ] if yes, merge PR to master
     - [ ]  if no, make a comment and request that developer make changes to pass tests 
- [ ]   As a peer reviewer, Pull down latest version of CNF conformance test code from `master` branch
- [ ]  Run `shards install`

### Spec test should pass
- [ ]  Run `crystal spec`
- [ ]  I expect to see PASSED for the test

### Update Prerequisite checker
- [ ] N/A

### Update yml validator, if needed
- [ ] N/A

### I would expect to see a test of a CNF in an airgapped environment:
- [ ]  `./cnf-testsuite airgapped output-file=./tmp/airgapped.tar.gz`
- [ ]  `./cnf-testsuite setup offline=./tmp/airgapped.tar.gz`
- [ ] `./cnf-testsuite cnf_setup cnf-path=sample-cnfs/sample_coredns`
- [ ] `./cnf-testsuite workload offline=true`

### Screenshots of publish tarball test:
- [ ] I can see a screenshots of SUCCESS of the publish tarball.

**Comment by agentpoyo** [comment]
We should probably suppress these std out messages, looks like it tries to first delete a file that's not present and then curl status output:

![585_airgap_outputfile_stdout](https://user-images.githubusercontent.com/14348948/120730841-ff7e9380-c4a7-11eb-83a2-ebd597932cfc.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/120743463-ad953800-c4be-11eb-8a67-0cc35d1d41ac.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/120743557-de756d00-c4be-11eb-974f-95340ba1f0af.png)

**Comment by agentpoyo** [comment]
![image](https://user-images.githubusercontent.com/14348948/120744932-b2a7b680-c4c1-11eb-836f-aa9e39254061.png)

**Comment by taylor** [comment]
@wavell @agentpoyo Is this now ready for end-users such as Swisscom and Orange to try?

**Comment by clementnuss** [comment]
Hi @taylor, thanks for all the work you've done there!
Unfortunately I won't be able to test this myself, as I don't have the resources (Cluster) anymore, and because I'll leave Swisscom in a few months.
I however initiated a handover of this project to fellow colleagues, and they'll. hopefully be able to report on the new functionality in a couple of weeks!

**Comment by taylor** [comment]
Thanks for the info, @clementnuss. 

I'm open to giving an intro and demo to your fellow colleagues. You can reach out to me via email and we can schedule something.

The test suite itself is ready to be used in air-gapped environment now if the CNFs are installed  in a "local" image registry in the air-gapped environment or if someone manually caches the images on the nodes. We have a new feature in-progress (#795) that will support automatically distributing a target CNF to the K8s nodes image cache for those not running a local image registry. 

Let me know about the demo for your colleagues.

Good luck with your new venture (after Swisscom).

**Comment by taylor** [comment]
Air-gapped support for the test suite compete and in [v0.12.0](https://github.com/cncf/cnf-testsuite/releases/tag/v0.12.0)
