### ISSUE TITLE
[Contributors] Select one hour per week to hold CNF Test Suite "Office Hours"

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#850]
### [Contributing] Select one hour per week to hold CNF Test Suite "Office Hours"

To help contributors of the CNF Test Suite with their journey, we would like to hold regular
office hours.

Office hours will be an opportunity to discuss how to get started, share
implementation tips and blockers, and have a shared understanding of the CNF Test Suite workflow

To start, we can meet once per week, for one hour. 

### Tasks: 

- [ ] Create a doodle poll with possible options (@lixuna) 
- [ ] Vote on time slot(s) that work best with your calendar
- [ ] Select zoom url for CNF Test Suite "Office Hours"
- [ ] Add Office Hours time and location to recurring meeting notes and demo slide decks

**Comment by lixuna** [comment]
Please vote on time slot(s) that work best with your calendar (ie. Thursdays at 15:00 UTC (10:00am CDT))

- https://doodle.com/poll/tihtuamypzi743br

**Comment by lixuna** [comment]
The Doodle poll has been updated with this week's options. 
https://doodle.com/poll/tihtuamypzi743br

If contributors are interested in setting a recurring time to collaborate, then weekly office hours will be reserved. 

Doodle poll will be closed on Friday, Aug 20 at 12pm CDT.
