### ISSUE TITLE
[Documentation] Create Calendly.com account for CNF Test Suite intro/demo meetings

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testsuite#852]
### Short description: 
- to help schedule 45-minute CNF Test Suite intro calls, create a Calendly account with a limited set of recurring meeting time options, 1 or 2 times per week.

### Tasks: 

- [x] Select/create email address to use with new calendly account
- [x] Sign up 
- [x] Set up recurring meeting time options, from July 19 to September 30
- [x] Add Calendly URL to README
- [x] Add Calendly URL to CNF Test Suite demo slides

**Comment by lixuna** [comment]
https://calendly.com/cnftestsuite

<img width="1031" alt="Screen Shot 2021-07-14 at 3 38 43 PM" src="https://user-images.githubusercontent.com/11701267/125689877-63b525e8-141b-4605-be46-6496cb503c59.png">

**Comment by lixuna** [comment]
"Schedule a demo" with calendly link added to shared slide deck 

<img width="737" alt="Screen Shot 2021-07-15 at 4 13 55 PM" src="https://user-images.githubusercontent.com/11701267/125858594-a9417f5a-52b6-4ae4-bbde-9433a18139d6.png">
